project/scraper/views.py
from flask import Blueprint, url_for, render_template, redirect, request
import requests
import json
import pandas as pd
import os

# database config
from project import db
from project.models.models import Records

# headers
headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'cache-control': 'max-age=0',
    'cookie': '__cfduid=d83673cf7d88f3d5743df615d2a3c68961601514796; _shopify_y=239022ca-28a9-4e23-b486-f896c1203ace; cart_currency=USD; secure_customer_sig=; _y=239022ca-28a9-4e23-b486-f896c1203ace; _shopify_fs=2020-10-01T01%3A13%3A16Z; _orig_referrer=https%3A%2F%2Fwww.google.com%2F; _landing_page=%2F; _s=0fb9bd47-c203-4dff-9c18-8502ff0eba62; _shopify_s=0fb9bd47-c203-4dff-9c18-8502ff0eba62; _shopify_sa_p=; SL_GWPT_Show_Hide_tmp=1; SL_wptGlobTipTmp=1; shopify_pay_redirect=pending; cart_sig=; _privy_C5A3105DD4E222601F5686EE=%7B%22uuid%22%3A%22f4961ba4-313b-4ca4-b85b-1afc49c7a5fd%22%2C%22cart_value%22%3A0%2C%22variations%22%3A%7B%7D%2C%22country_code%22%3A%22ID%22%2C%22region_code%22%3A%22ID_%22%2C%22postal_code%22%3A%22%22%7D; privy_suppress_1018995=1601514809; _shopify_sa_t=2020-10-01T01%3A37%3A30.601Z; amplitude_id_0d882e02683d5df9d3e5364fb895c64fhelmboots.com=eyJkZXZpY2VJZCI6IjM3YzNiNmEyLThlNmMtNDgxMy1iMTBkLTU5MDI1YWRjNDY3NlIiLCJ1c2VySWQiOiJmZDJkODdlNi1iNjM2LTQ1ZDMtOWExMS1kMTUwNzMzMGE0MzAiLCJvcHRPdXQiOmZhbHNlLCJzZXNzaW9uSWQiOjE2MDE1MTQ4MDQyNTQsImxhc3RFdmVudFRpbWUiOjE2MDE1MTYyNTM4MzgsImV2ZW50SWQiOjgsImlkZW50aWZ5SWQiOjI0LCJzZXF1ZW5jZU51bWJlciI6MzJ9; _shopify_tm=; _shopify_m=persistent; _shopify_tw=',
    'if-none-match': 'cacheable:939c41f2c66d4fd95e26236e1343d466',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': 'upgrade-insecure-requests',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
}

# blueprint
scraper_blueprint = Blueprint('scraper', __name__, template_folder='templates')


# helper
def get_detail(limit, page):
    global images
    params = {
        'limit': limit,
        'page': page
    }

    # scraping process

    # define url
    url = 'https://helmboots.com/products.json'
    source = requests.get(url, params=params, headers=headers)
    data = source.json()

    # product list
    product_list = []

    # scraping step
    for item in data['products']:
        title = item['title']
        handle = item['handle']
        publish = item['published_at']
        product_type = item['product_type']
        vendor = item['vendor']

        for image in item['images']:
            try:
                images = image['src']
            except:
                images = 'no image found'
        for variant in item['variants']:
            sku = variant['sku']
            price = variant['price']
            product_id = variant['product_id']

            # save product
            product = {
                'title': title,
                'handle': handle,
                'publish': publish,
                'product_id': product_id,
                'price': price,
                'product type': product_type,
                'sku': sku,
                'vendor': vendor,
                'image url': images
            }

            product_list.append(product)
        return product_list


# creating route
@scraper_blueprint.route('/')
def home():
    records = Records.query.all()
    return render_template('index.html', records=records)


@scraper_blueprint.route('/get-data')
def get_data_product():
    url = 'https://helmboots.com/products.json/'
    source = requests.get(url)
    data = source.json()

    # save to json file
    try:
        # creating directory
        os.makedirs('results')
    except FileExistsError:
        pass
    with open('results/source_data.json', 'w') as outfile:
        json.dump(data, outfile)
    print('data saved successfully')

    return redirect(url_for('scraper.home'))


# route to view data
@scraper_blueprint.route('/view-data', methods=['GET', 'POST'])
def view_data():
    global images

    if request.method == 'POST':
        list_product = get_detail(limit=request.form['limitvalue'], page=request.form['pagedisplay'])
        for value in list_product:
            title = value['title']
            handle = value['handle']
            publish = value['publish']
            product_id = value['product_id']
            price = value['price']
            product_type = value['product type']
            sku = value['sku']
            vendor = value['vendor']
            image_url = value['image url']

            # save to database
            new_records = Records(title=title, handle=handle, product_id=product_id, price=price, publish=publish,
                                  product_type=product_type, sku=sku, vendor=vendor, image_url=image_url)
            db.session.add(new_records)
            db.session.commit()

        print('data saved to database')

        # save to csv
        df = pd.DataFrame(list_product)
        df.to_csv('./results/result.csv')
        print('data saved to csv success')
        return redirect(url_for('scraper.home'))

    return render_template('view-data.html')

project/scraper/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='bulma/css/bulma.min.css') }}">
    </head>
    <body>
        <!-- section jumboron hero -->

        <!-- navbar section -->
        <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
          <div class="navbar-brand">
            <a class="navbar-item" href="{{ url_for('scraper.home') }}">
              <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
              <p class="subtitle has-text-dark has-text-weight-bold">HelmBoots Scraper</p>
            </a>
        
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
        
          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
              <a href="{{ url_for('scraper.get_data_product') }}" class="navbar-item">Get Product Data</a>
              <a href="{{ url_for('scraper.view_data') }}" class="navbar-item">View Data Product</a>
            </div>
        
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="buttons">
                  <a href="https://gitlab.com/perymerdeka/helmboots-scraper" class="button is-primary"><strong>View Source Code</strong></a>
                  <a href="https://gitlab.com/perymerdeka/helmboots-scraper/-/archive/master/helmboots-scraper-master.zip" class="button is-light">Download Source Code</a>
                </div>
              </div>
            </div>
          </div>
        </nav>
        <!-- end navbar section -->

        <section class="hero is-medium is-dark is-bold">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title"><a class="has-text-white" href="{{ url_for('scraper.home') }}">Welcome to HelmBoot Scraper</a></h1>
                    <h2 class="subtitle">Web Home Page</h2>
                    <button class="button is-primary has-text-centered is-center"><a class=" has-text-white" href="#results">View Result</a></button>
                </div>
            </div>
        </section>
        <!-- end section jumboton hero -->

        <!-- section feature -->
        <section class="hero hero-body">

        </section>
        <!-- end section feature -->

        <!-- table section -->
        <section class="hero" id="results">
            <div class="hero-body">
                <h1 class=" has-text-centered title">Table Result Scraper</h1>
                <table class="table has-text-centered">
                    <thead>
                        <tr>
                            <th><abbr title="Number">No. </abbr></th>
                            <th>Title</th>
                            <th>Handle</th>
                            <th>Date Published</th>
                            <th>Product Identity</th>
                            <th>Price</th>
                            <th>Product Type</th>
                            <th>SKU</th>
                            <th>Vendor Brand</th>
                            <th>Image Url</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for result in records %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ result.title }}</td>
                            <td>{{ result.handle }}</td>
                            <td>{{ result.publish }}</td>
                            <td>{{ result.product_id }}</td>
                            <td>{{ result.price }}</td>
                            <td>{{ result.product_type }}</td>
                            <td>{{ result.sku }}</td>
                            <td>{{ result.vendor }}</td>
                            <td><a href="{{ result.image_url }}">{{result.image_url}}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
        <!-- end table section -->

        <!-- footer section -->
        <section class="hero are-small">
            <footer class="footer">
                <div class="content has-text-centered">
                    <p><strong>HelmBoot Scraper</strong> available @ <a href="https://gitlab.com/perymerdeka" target="blank">Gitlab</a></p>
                </div>
            </footer>
        </section>
        <!-- end footer section -->
        
    </body>
</html>

project/scraper/templates/view-data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Data</title>
    
    <!-- add bulma css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bulma/css/bulma.min.css') }}">
</head>
<body>
  <!-- navbar section -->
  <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{{ url_for('scraper.home') }}">
        <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
        <p class="subtitle has-text-dark has-text-weight-bold">HelmBoots Scraper</p>
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a href="{{ url_for('scraper.get_data_product') }}" class="navbar-item">Get Product Data</a>
        <a href="{{ url_for('scraper.view_data') }}" class="navbar-item">View Data Product</a>
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a href="https://gitlab.com/perymerdeka/helmboots-scraper" class="button is-primary"><strong>View Source Code</strong></a>
            <a href="https://gitlab.com/perymerdeka/helmboots-scraper/-/archive/master/helmboots-scraper-master.zip" class="button is-light">Download Source Code</a>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <!-- end navbar section -->

  <!-- form section -->
    <section class="hero is-medium">
      <div class="hero-body">
        <p class="subtitle has-text-centered has-text-weight-bold">Setting Limit Value</p>
        <div class="container">
          <form action="{{ url_for('scraper.view_data') }}" method="POST">
            <div class="field">
              <label class="label" for="limit-value">Set Limit Value:</label>
              <div class="control">
                <input class="input" type="text" id="limit-value" name="limitvalue" value=""><br>
              </div>
            </div>
            <div class="field">
              <label class="label" for="page-display">Set Page Display:</label>
              <div class="control">
                <input class="input" type="text" id="page-display" name="pagedisplay" value="">
              </div>
            </div>
            <input class="button is-primary" type="submit" value="Submit">
          </form>
        </div>
      </div>
    </section>
  <!--  end form section  -->

  <!-- footer section -->
  <section class="hero are-small">
    <footer class="footer">
        <div class="content has-text-centered">
            <p><strong>HelmBoot Scraper</strong> available @ <a href="https://gitlab.com/perymerdeka" target="blank">Gitlab</a></p>
        </div>
    </footer>
  </section>
  <!-- end footer section -->
</body>
</html>